name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download project ZIP
      uses: actions/checkout@v4

    - name: Extract project
      run: |
        unzip -q akinhub.zip -d project

    - name: Setup Google Services and Keystore
      run: |
        # 1. Create google-services.json in app folder
        mkdir -p project/app/src/debug project/app/src/release
        cat << 'EOF' > project/app/google-services.json
        {
          "project_info": {
            "project_number": "655465843475",
            "project_id": "akinhub-3f2da",
            "storage_bucket": "akinhub-3f2da.firebasestorage.app"
          },
          "client": [
            {
              "client_info": {
                "mobilesdk_app_id": "1:655465843475:android:5db686bdb9b2519a06e8e6",
                "android_client_info": {
                  "package_name": "com.aistudio.akinhub.dzrxkp"
                }
              },
              "oauth_client": [],
              "api_key": [
                {
                  "current_key": "AIzaSyBx3T-4y54QN1R2QoaVSW5K43P9QgESgkU"
                }
              ],
              "services": {
                "appinvite_service": {
                  "other_platform_oauth_client": []
                }
              }
            }
          ],
          "configuration_version": "1"
        }
        EOF
        cp project/app/google-services.json project/app/src/debug/google-services.json
        cp project/app/google-services.json project/app/src/release/google-services.json
        
        # 2. Generate debug.keystore directly inside project/ root folder
        keytool -genkey -v -keystore project/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: '17'

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v6
      with:
        gradle-version: '9.3.1'

    - name: Install Virtual Display (Xvfb)
      run: sudo apt-get update && sudo apt-get install -y xvfb

    - name: Build Debug APK
      working-directory: project
      run: xvfb-run gradle assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v7
      with:
        name: Akash-Internet-Hub-APK
        path: project/app/build/outputs/apk/debug/*.apk
        archive: false
